# Generated by Django 4.1.7 on 2023-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Login",),
    ]
