# Generated by Django 4.1.7 on 2023-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="appform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("address", models.TextField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("phoneno", models.IntegerField()),
                ("gender", models.BooleanField()),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("a", "Savings"),
                            ("b", "Current"),
                            ("c", "Fixed"),
                            ("d", "Salary"),
                        ],
                        max_length=100,
                    ),
                ),
                ("material", models.CharField(default=True, max_length=50)),
                ("district", models.CharField(max_length=250)),
                ("branch", models.CharField(max_length=250)),
            ],
        ),
    ]
